/hippo:configuration:
  jcr:primaryType: hipposys:configuration
  /hippo:derivatives:
    jcr:primaryType: hipposys:derivativesfolder
    /hippo:corederivatives:
      jcr:primaryType: hipposys:deriveddefinition
      hipposys:classname: org.hippoecm.repository.deriveddata.CoreDerivedDataFunction
      hipposys:nodetype: hippo:document
      hipposys:serialver: 1
      /hipposys:accessed:
        jcr:primaryType: hipposys:propertyreferences
        /ancestors:
          jcr:primaryType: hipposys:builtinpropertyreference
          hipposys:method: ancestors
      /hipposys:derived:
        jcr:primaryType: hipposys:propertyreferences
        /ancestors:
          jcr:primaryType: hipposys:relativepropertyreference
          hipposys:relPath: hippo:paths
    /date:
      jcr:primaryType: hipposys:deriveddefinition
      hipposys:classname: org.hippoecm.faceteddate.DerivedDataFunction
      hipposys:nodetype: hippostd:date
      hipposys:serialver: 1
      /hipposys:accessed:
        jcr:primaryType: hipposys:propertyreferences
        /date:
          jcr:primaryType: hipposys:relativepropertyreference
          hipposys:relPath: hippostd:date
      /hipposys:derived:
        jcr:primaryType: hipposys:propertyreferences
        /year:
          jcr:primaryType: hipposys:relativepropertyreference
          hipposys:relPath: hippostd:year
        /month:
          jcr:primaryType: hipposys:relativepropertyreference
          hipposys:relPath: hippostd:month
        /weekofyear:
          jcr:primaryType: hipposys:relativepropertyreference
          hipposys:relPath: hippostd:weekofyear
        /dayofweek:
          jcr:primaryType: hipposys:relativepropertyreference
          hipposys:relPath: hippostd:dayofweek
        /dayofmonth:
          jcr:primaryType: hipposys:relativepropertyreference
          hipposys:relPath: hippostd:dayofmonth
        /dayofyear:
          jcr:primaryType: hipposys:relativepropertyreference
          hipposys:relPath: hippostd:dayofyear
        /hourofday:
          jcr:primaryType: hipposys:relativepropertyreference
          hipposys:relPath: hippostd:hourofday
        /minute:
          jcr:primaryType: hipposys:relativepropertyreference
          hipposys:relPath: hippostd:minute
        /second:
          jcr:primaryType: hipposys:relativepropertyreference
          hipposys:relPath: hippostd:second
    /reviewed-action:
      jcr:primaryType: hipposys:deriveddefinition
      hipposys:classname: org.onehippo.repository.documentworkflow.DerivedDataFunction
      hipposys:nodetype: hippostd:publishableSummary
      hipposys:serialver: 1
      /hipposys:accessed:
        jcr:primaryType: hipposys:propertyreferences
        /publishedAvailability:
          jcr:primaryType: hipposys:resolvepropertyreference
          hipposys:relPath: ../{.}[@hippostd:state='published']/hippo:availability
        /publishedLastModified:
          jcr:primaryType: hipposys:resolvepropertyreference
          hipposys:relPath: ../{.}[@hippostd:state='published']/hippostdpubwf:lastModificationDate
        /unpublishedLastModified:
          jcr:primaryType: hipposys:resolvepropertyreference
          hipposys:relPath: ../{.}[@hippostd:state='unpublished']/hippostdpubwf:lastModificationDate
      /hipposys:derived:
        jcr:primaryType: hipposys:propertyreferences
        /summary:
          jcr:primaryType: hipposys:relativepropertyreference
          hipposys:relPath: hippostd:stateSummary
